libaio: harness: fix build error due to linker search order
Move '-lpthread' after 'main.c' in the compiler command line, so that
the linker can search unresolved symbols from the test in the library.

    cases/18.t:98: undefined reference to `pthread_create'
    cases/18.t:103: undefined reference to `pthread_join'
    collect2: error: ld returned 1 exit status

Signed-off-by: Mauricio Faria de Oliveira <mauricfo@linux.vnet.ibm.com>
Signed-off-by: Jeff Moyer <jmoyer@redhat.com>